### ISSUE TITLE
1.84版本提示script build failed

### ISSUE THREAD

**Issue by zhixuan45** [Joblesskov/red_alert#1]
![screenshot0](https://github.com/user-attachments/assets/b16da063-bb67-4ec7-a78b-cd72128ed8a4)

**Comment by Joblesskov** [comment]
将rwr更新到1.98版本

**Comment by zhixuan45** [comment]
> 将rwr更新到1.98版本

![image](https://github.com/user-attachments/assets/93375dc0-ade9-47e8-a6fc-f88a2ecf9a24)
从朋友那拿了一份1.98.1的，但是还是一样

**Comment by Joblesskov** [comment]
首先检查mod文件夹名字是否为"red_alert"并且放在了"RunningWithRifles\media\packages"。
如果这样无法解决，找到"C:\Users\用户名\AppData\Roaming\Running with rifles\rwr_game.log"，用记事本打开，搜索“script build failed”，告诉我这段报错的之前几行输出是什么。

**Comment by zhixuan45** [comment]
![image](https://github.com/user-attachments/assets/daf0b415-6dcf-4100-8d78-e92809404385)
找不到

**Comment by Joblesskov** [comment]
> ![image](https://private-user-images.githubusercontent.com/78686872/361353472-daf0b415-6dcf-4100-8d78-e92809404385.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NTkwNDAsIm5iZiI6MTcyNDY1ODc0MCwicGF0aCI6Ii83ODY4Njg3Mi8zNjEzNTM0NzItZGFmMGI0MTUtNmRjZi00MTAwLThkNzgtZTkyODA5NDA0Mzg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDA3NTIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhNmE2YWZmMTcwOTYyZDBlZDk2ZjJlMzJiMmU3YzQyYTFkM2ZmZmYxNWJmMGI1NzQ2ZTIxNjMwM2M1MGY2MTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0qiDHBYNw-TdGxj5Tp-rTBjYMerTmvQNHdpeh7PCLN0) 找不到

不是rwr_config而是rwr_game

**Comment by zhixuan45** [comment]
重新安装了一下包体，发现没有删掉下载后缀的main
或许应该在markdown中加粗一下

**Comment by zhixuan45** [comment]
我会尝试一下1.84能不能装上的
